name: Deploy

on:
  push:
    branches:
      - master

jobs:
 custom-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: Install heroku cli
        run: npm install -g heroku
      - name: Heroku login credentials
        run: |
          cat > ~/.netrc <<EOF
            machine api.heroku.com
              login $HEROKU_EMAIL
              password $HEROKU_API_KEY
            machine git.heroku.com
              login $HEROKU_EMAIL
              password $HEROKU_API_KEY
          EOF
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}
      - name: Whoaim
        run: heroku auth:whoami
        env:
          HEROKU_APP_NAME: ${{ secrets.HEROKU_APP }}
      - name: Add Heroku remote
        run: heroku git:remote --app $HEROKU_APP
        env:
          HEROKU_APP_NAME: ${{ secrets.HEROKU_APP }}
      - name: Push to Heroku
        run: git push heroku master
